layouts:
    - column
    - fullscreen
    - wide
    - 3column-middle

# setup modifiers
mod1: # settings, screens
    - option
    - shift
mod2: # focus
    - option
    - command
mod3: # windows
    - control
    - option
mod4: # spaces
    - control
    - shift    

# commands
relaunch-amethyst:
    mod: mod1
    key: z
toggle-tiling:
    mod: mod1
    key: t
reevaluate-windows:
    mod: mod1
    key: r
cycle-layout:
    mod: mod1
    key: right
cycle-laoyout-backward:
    mod: mod1
    key: left 
shrink-main:
    mod: mod3
    key: down
expand-main:
    mod: mod3
    key: up
focus-ccw:
    mod: mod2
    key: left
focus-cw:
    mod: mod2
    key: right
focus-main: 
    mod: mod2
    key: m
foucs-screen-ccw:
    mod: mod1
    key: left
focus-screen-cw:
    mod: mod1
    key: right
swap-screen-ccw:
    mod: mod1
    key: up
swap-screen-cw:
    mod: mod1
    key: down
swap-ccw:
    mod: mod3
    key: left
swap-cw:
    mod: mod3
    key: right
swap-main:
    mod: mod3
    key: m
throw-space-left:
    mod: mod4
    key: left
throw-space-right:
    mod: mod4
    key: right
throw-space-1:
    mod: mod4
    key: 1
throw-space-2:
    mod: mod4
    key: 2
throw-space-3:
    mod: mod4
    key: 3
throw-space-4:
    mod: mod4
    key: 4


# Mouse settings
mouse-follows-focus: false
focus-follows-mouse: false
mouse-swaps-windows: true
mouse-resizs-windows: true

# Add 8px margin between windows
window-margins: true
window-margin-size: 8
smart-window-margins: true
