theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "custom" 
command = "~/.config/i3/tools/isIntlLayout.sh"
on_click = "~/.config/i3/tools/toggleLayout.sh"
interval = 1

[[block]]
block = "net"
device = "enx98e743b8e8f2"
speed_up = false
speed_down = true
interval = 1

[[block]]
block = "net"
device = "wlp59s0"
speed_up = false
speed_down = false
ssid = true
interval = 1

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "backlight"

[[block]]
block = "sound"
name = "alsa_output.pci-0000_00_1f.3.analog-stereo"

[[block]]
block = "battery"
format = "{percentage}% ({time}h)"

[[block]]
block = "time"
interval = 60
format = "%a %F (w%W) %R"
